### ISSUE TITLE
[Question]: What about rewriting everything in Qt?

### ISSUE THREAD

**Issue by Green0wl** [eyelash/platon-gtk#2]
According to what you wrote [here](https://github.com/eyelash/platon-core/pull/1#issuecomment-1975152619), you'd like to get rid of Vala. I thought I'd suggest you switch to Qt. How would you respond to that?

**Comment by eyelash** [comment]
The Vala code has already been removed. The idea of platon is that the majority of the logic [lives in a separate repository that does not depend on any GUI framework](https://github.com/eyelash/platon-core). The GUIs are then a thin layer on top and there could be many different GUIs (GTK, Qt, Windows, macOS, web, Flutter, Java, etc.). This repository, as the name suggests, is focussed on GTK. I thought about writing a Qt GUI, but it should definitely live in a separate repository. Right now, my focus is on prism and the core. If you're interested in C++ an Qt then writing a separate Qt GUI for platon might be an interesting project for you. I hope this answers your question :)
